### ISSUE TITLE
Simple Indoors shows KF/ToT with shuffled spawns

### ISSUE THREAD

**Issue by fenhl** [mracsys/tootr#1]
1. Reset
2. Set Shuffle Interiors to Simple
3. Kokiri Forest, Temple of Time, and Temple of Time Entrance regions are shown even though spawns are shuffled.

**Comment by mracsys** [comment]
I believe this is a side effect of some logic to force these areas to be visible when spawns aren't shuffled. In that case I hide the Spawn Points area and use Kokiri Forest and Temple of Time Entrance as starting points for area visibility. I tried to do this somewhat generically instead of hardcoding the areas, which makes it way more complicated than it needs to be.

**Comment by mracsys** [comment]
Quick update on this. I've resolved the issue in the item_tracking branch. It's part of a major refactor to optimize responsiveness in preparation for item/logic tracking. I've pushed the source but won't redeploy to the live site until I've had a few weeks to test for regressions.
