### ISSUE TITLE
Valley To Lake Shuffle Broken

### ISSUE THREAD

**Issue by KankuroGB** [mracsys/tootr#37]
It doesn't let me change the GV to LH shuffle unless I turn all overworld shuffles on.
Turning on the `Shuffle Valley/Lake` option doesn't seem to change anything, as you can see below

![image](https://user-images.githubusercontent.com/17660872/224299362-3e5bc49d-2bb4-44a9-866e-a25357032b17.png)

**Comment by mracsys** [comment]
I thought it worked as an extension to OW ER like Hideout ER is an extension to Interior ER. Can't say I'm a fan of that implementation, but I'll push an update to make it work.

**Comment by KankuroGB** [comment]
Not sure if it is related or not, but I also can't seem to pick interiors for the GV > LH exit. even though that is what my seed gave me. I go from GV to Impa's House (Front).

**Comment by mracsys** [comment]
This should be fixed in the latest update.

The GV > LH exit used to be an overworld type that was mutually exclusive with all other entrances, unlike the one ways like owl drops. This is how it worked on Roman's fork prior to the new feature from the main fork getting merged. I have an open PR to main to restrict the entrance pool for this entrance to exteriors to be more consistent with the other shuffle designs. If it's merged there will be another update to this issue.

Thanks for the report!
